### ISSUE TITLE
The onfta-crawler git repository could not be found

### ISSUE THREAD

**Issue by zeonn** [khainguyen95/django-dynamic-scraper#1]
trying to run step 2 from manual (clone git onfta-crawler).

$ git clone git@gitlab.com:hv-db04/onfta-crawler.git
Cloning to «onfta-crawler»…
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by khainguyen95** [comment]
project  là riêng tư. vui lòng sử dụng project của bạn.

**Comment by khai-nguyen-dinh** [comment]
project is private. Please use your project.

**Comment by zeonn** [comment]
ok. Sorry.
